project_id = "wnbynyymqhkestmkcenj"

[functions.verify-bsc-payment]
verify_jwt = false

[functions.forex-prices]
verify_jwt = false

[functions.korapay-webhook]
verify_jwt = false

[functions.admin-snapshot]
verify_jwt = false

[functions.admin-affiliate]
verify_jwt = false

[functions.admin-account]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false
