import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";

const sections = [
  ["1. Scope of this policy", "This Privacy Policy explains how PrimePips Funding (PrimePips, we, us, or our) collects, uses, discloses, stores, and protects personal information when you visit our website, create an account, purchase or use our simulated trading skills services, contact support, or otherwise interact with us (collectively, the Services).\n\nThis policy should be read with our Terms and Conditions and any product-specific notices. If a notice presented at collection conflicts with this policy, the more specific notice applies to the information and purpose described there."],
  ["2. The information we collect", "We collect information you provide directly, such as your name, email address, country, account credentials, billing details, support messages, survey responses, referral information, and information you submit during an identity or payment review. Do not send passwords, authentication codes, private keys, or full payment credentials in a message.\n\nWe also collect information generated through use of the Services, including account status, simulated trades, orders, balances, scores, challenge activity, rule events, login history, device and browser details, IP address, approximate location, timestamps, pages viewed, referral source, error reports, and interactions with notifications. Some information is collected automatically through cookies, local storage, logs, pixels, and similar technologies."],
  ["3. Simulated trading data", "PrimePips provides simulated trading skills assessments. We process account activity, simulated orders, performance calculations, rule events, and related records to operate the platform, display results, assess compliance with product rules, troubleshoot issues, prevent abuse, and improve the Services. These records describe activity in a simulation and are not records of live trades or real investment assets.\n\nWe may analyze aggregated or de-identified performance patterns to understand product quality, platform reliability, educational usefulness, and rule clarity. We do not use simulated results to promise a real financial return. The Terms and Conditions explain the simulated nature of the accounts and the absence of an expectation of real rewards."],
  ["4. How we use information", "We use personal information to create and administer accounts; authenticate users; provide dashboards, charts, and simulated assessments; process purchases; respond to support requests; send service notices; monitor account integrity; investigate suspected fraud or abuse; enforce our Terms and product rules; maintain backups and audit records; diagnose errors; secure our systems; understand usage; improve features; personalize non-essential communications where permitted; and comply with law.\n\nWe may also use information to communicate about products, offers, surveys, or educational content where permitted. You can opt out of marketing communications using the unsubscribe control in the message or by contacting support. You will continue to receive essential account, security, transaction, and service communications."],
  ["5. Legal bases", "Where applicable law requires a legal basis, we process information because it is necessary to perform a contract with you, to take steps at your request before entering a contract, to comply with a legal obligation, to protect our legitimate interests, or with your consent. Our legitimate interests may include operating and securing the Services, preventing fraud, enforcing agreements, responding to complaints, improving reliability, and defending legal claims.\n\nWhere we rely on consent, you may withdraw it through the method provided. Withdrawal does not affect processing that occurred before withdrawal or processing based on another lawful basis. Some information is required to provide a requested Service; if you do not provide it, we may be unable to create an account, process a payment, complete verification, or respond to a request."],
  ["6. Cookies and similar technologies", "We use essential technologies to keep you signed in, protect sessions, remember preferences, route requests, detect abuse, and make core features work. We may also use analytics or measurement technologies to understand traffic, errors, performance, and feature usage. The technologies available may change as the Services and providers change.\n\nYou can control cookies through browser settings and, where available, a consent control. Blocking essential technologies may prevent login, payments, dashboards, or other features from working. Browser-based signals and privacy settings may affect how preferences are recorded. We do not treat a browser setting as permission to ignore a legally required preference."],
  ["7. Payments and financial information", "Payments may be processed by third-party payment providers. We may receive transaction identifiers, payment status, amount, currency, payment method type, billing country, risk signals, and limited payment details needed to reconcile a purchase. We generally do not need or intend to store full card numbers, card security codes, bank passwords, wallet recovery phrases, or other complete payment secrets.\n\nPayment providers may collect and process information under their own privacy policies. We use payment information to confirm transactions, activate or restrict access, investigate reversals and disputes, prevent fraud, provide refunds where applicable, and maintain accounting records. Contact the payment provider directly for questions about information it controls."],
  ["8. Identity, age, and fraud checks", "We may request identity, age, location, payment ownership, or other verification information when needed to protect an account, comply with law, investigate fraud, or enforce product eligibility. We may use third-party verification and fraud-prevention providers for these checks. The information requested should be submitted only through an authorized verification flow.\n\nWe may compare information across transactions, accounts, devices, and activity patterns to identify account sharing, impersonation, unauthorized payments, coordinated abuse, sanctions concerns, or attempts to circumvent a restriction. A review or temporary hold is not necessarily a finding of wrongdoing. We limit access to review information and retain it according to legal, security, and operational requirements."],
  ["9. When we share information", "We share information with service providers that help us host, secure, authenticate, analyze, support, communicate with users, process payments, provide market data, operate charts, prevent fraud, and maintain the Services. Providers may process information only as needed for their contracted services and subject to appropriate obligations.\n\nWe may disclose information to professional advisers, insurers, auditors, corporate affiliates, regulators, courts, law enforcement, payment networks, or other parties when required by law, legal process, security needs, fraud prevention, an emergency, or the protection of rights and property. We may also disclose information in connection with a merger, financing, acquisition, restructuring, sale of assets, or transfer of the Services, subject to applicable law."],
  ["10. International transfers", "Our providers or affiliates may process information in countries other than the country where you live. Where applicable law requires safeguards for international transfers, we will use an approved transfer mechanism or another lawful safeguard. The protections in the destination country may differ from those in your country.\n\nBy using the Services, you understand that information may be processed through infrastructure and providers located internationally. You can contact us about applicable transfer safeguards or available information about the locations and categories of providers involved, subject to security and confidentiality limits."],
  ["11. How long we keep information", "We retain information for as long as reasonably necessary for the purposes described in this policy, including to provide the Services, maintain account and payment records, resolve disputes, investigate abuse, preserve audit trails, comply with legal and tax obligations, enforce agreements, and establish or defend claims. Retention periods vary depending on the type, sensitivity, and purpose of the information.\n\nWhen information is no longer needed, we may delete it, anonymize it, or securely isolate it. Deleting a dashboard item or closing an account may not immediately delete system records that must be retained for legal, security, accounting, or dispute-resolution purposes."],
  ["12. Security", "We use administrative, technical, and physical safeguards designed to protect personal information against unauthorized access, loss, misuse, alteration, and disclosure. Safeguards may include access controls, authentication, logging, encryption in transit where supported, provider reviews, backups, monitoring, and incident-response procedures.\n\nNo online service is completely secure. You are responsible for using a strong unique password, protecting authentication codes, securing your Devices, avoiding suspicious links, and notifying us promptly about suspected account takeover or unauthorized activity. Never send a password, one-time code, private key, or recovery phrase to support."],
  ["13. Your privacy rights", "Depending on your location, you may have rights to request access to personal information, correction of inaccurate information, deletion, restriction of processing, portability, objection to certain processing, withdrawal of consent, or review of an automated decision. You may also have the right to complain to a data-protection authority. These rights are subject to legal exceptions and verification requirements.\n\nTo make a request, contact us through the official support or contact channel and identify the account email, the right you are exercising, and the information relevant to the request. We may ask for additional information to verify identity and protect against unauthorized disclosure. An authorized representative may need to provide evidence of authority."],
  ["14. Children", "The Services are not directed to children below the minimum age required to create an account or enter a contract in their jurisdiction. We do not knowingly request or intentionally collect personal information from a child in violation of applicable law. If you believe a child has provided information or created an account, contact support with enough detail for us to investigate.\n\nIf we learn that we collected information from a child when collection was not permitted, we will take reasonable steps to delete it or otherwise handle it as required by law. Parents and guardians should supervise use of Devices and payment methods associated with their household."],
  ["15. Communications and marketing choices", "We may send transactional communications about account access, security, payments, challenge status, rule changes, support, and service availability. These messages are necessary to operate the Services and generally cannot be disabled while you maintain an account.\n\nMarketing messages are optional where required by law. You can unsubscribe using the link in the message or contact support. An opt-out may take a reasonable period to process, and you may still receive messages triggered before the request or messages that are strictly transactional."],
  ["16. Third-party services and links", "The Services may link to or integrate with third-party sites, payment providers, charting tools, analytics services, authentication systems, social networks, and other platforms. This policy does not govern information collected directly by a third party under its own policy. Review the third party's terms and privacy notice before using an integration or submitting information.\n\nWe are not responsible for the privacy, security, content, or practices of a third party we do not control. An integration may allow a provider to receive information about your account or activity according to permissions you authorize. Revoke permissions through the provider when you no longer want the integration connected."],
  ["17. Do-not-track and signals", "Browsers and Devices may send privacy preferences or do-not-track signals. Because standards and provider implementations differ, our response may vary by technology, jurisdiction, and the purpose for which information is collected. We honor legally required consent and opt-out mechanisms where applicable.\n\nEssential processing needed for security, authentication, payments, and core functionality cannot be disabled through a general analytics preference. Contact support if you have a specific privacy preference or accessibility need that is not addressed by the available controls."],
  ["18. Changes to this policy", "We may update this Privacy Policy to reflect changes in the Services, providers, technology, legal requirements, or our information practices. The effective date at the top of this page identifies the current version. For material changes, we may provide additional notice through the Services or the email associated with your account where required or appropriate.\n\nReview this policy periodically. Your continued use of the Services after the effective date means the updated policy applies to future processing to the extent permitted by law. Where consent is required for a new use, we will request it through an appropriate mechanism."],
  ["19. Contact us", "For privacy questions, rights requests, complaints, or concerns about how information is handled, use the official contact or support channel published by PrimePips. Include the email address associated with your account and a clear description of your request, but do not include passwords, full card numbers, authentication codes, private keys, or unnecessary identity documents.\n\nWe may update our contact process as the Services develop. If you are unsatisfied with our response, you may have the right to contact the data-protection or privacy regulator in your jurisdiction."],
] as const;

export default function Privacy() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-20">
        <section className="border-b border-border bg-gradient-hero py-16">
          <div className="container mx-auto max-w-4xl px-4">
            <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-primary">Legal</p>
            <h1 className="mb-4 text-4xl font-serif font-bold text-foreground md:text-5xl">Privacy Policy</h1>
            <p className="text-muted-foreground">Effective date: August 19, 2026</p>
          </div>
        </section>
        <article className="container mx-auto max-w-4xl px-4 py-12">
          <div className="mb-12 border border-primary/40 bg-primary/10 p-6 text-foreground">
            <h2 className="mb-3 text-xl font-serif font-bold text-primary">Your information and the Services</h2>
            <p className="leading-7">PrimePips processes information to operate a simulated trading skills platform, provide account and payment functionality, secure the Services, and respond to users. We do not treat simulated account results as real investment assets or live-trading records.</p>
          </div>
          <div className="space-y-10">
            {sections.map(([title, content]) => (
              <section key={title}>
                <h2 className="mb-3 text-2xl font-serif font-semibold text-foreground">{title}</h2>
                <div className="space-y-4 text-[15px] leading-7 text-muted-foreground">
                  {content.split("\n\n").map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
                </div>
              </section>
            ))}
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
}