import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";

const sections = [
  ["1. Agreement and acceptance", "These Terms and Conditions govern your access to and use of the PrimePips Funding website, applications, trading interfaces, educational materials, challenge products, account dashboards, and related services (collectively, the Services). By creating an account, purchasing a challenge, accessing the Services, or selecting an acceptance checkbox, you agree to these Terms and Conditions and any policies incorporated into them.\n\nIf you do not agree with these Terms, do not register, purchase, fund, or use an account. We may update these Terms from time to time. The revised version applies from the date stated at the top of the page, except where applicable law requires another effective date. Your continued use of the Services after an update constitutes acceptance of the revised Terms."],
  ["2. Important nature of the Services", "PrimePips provides a skills-assessment and trading-simulation environment. The Services are designed to help users practise decision-making, risk management, discipline, and strategy execution using market data and simulated account conditions. The Services are not a bank account, brokerage account, investment account, deposit account, or offer of employment.\n\nA challenge fee or subscription fee is a fee for access to the applicable assessment, software, data, and services. It is not a capital contribution and does not create a fiduciary, partnership, agency, lending, investment, or profit-sharing relationship between you and PrimePips."],
  ["4. Eligibility and user account", "You must be legally capable of entering into a binding contract in your jurisdiction. You are responsible for providing accurate registration information, keeping it current, and ensuring that your use of the Services complies with the laws that apply to you. We may refuse registration or restrict access where use would violate law, sanctions, regulatory requirements, or our risk controls.\n\nYou may maintain only the accounts permitted by the product rules. Do not share credentials, transfer an account, allow another person to trade for you, or access another person's account without written authorization. You are responsible for all activity performed using your credentials and must notify us promptly if you suspect unauthorized access."],
  ["5. Purchase, pricing, and payment", "Prices, currencies, taxes, included features, account parameters, and billing intervals are presented at checkout. You authorize our payment providers and their partners to charge the selected payment method for the amount shown before confirmation. A payment may be subject to provider fees, exchange-rate differences, verification, limits, or delays outside our control.\n\nWe may correct pricing errors, decline transactions, request additional verification, or cancel an order where fraud, abuse, duplicate payment, technical error, or legal restrictions are reasonably suspected. A payment confirmation does not guarantee continued access if the transaction is reversed, disputed, refunded, or determined to be unauthorized."],
  ["6. Refunds and cancellations", "Refund eligibility is governed by the refund terms shown at checkout and any applicable refund policy. Unless that policy or mandatory law provides otherwise, fees are generally not refundable after access to a challenge or account has been delivered, used, or started. You must submit refund requests through the support channel specified by the Services and provide sufficient transaction details.\n\nChargebacks or payment disputes made without first contacting support may result in suspension while the transaction is investigated. Nothing in this section limits rights that cannot lawfully be excluded."],
  ["7. Trading rules and simulated performance", "Each product may have its own rules, including maximum drawdown, daily loss limits, profit targets, consistency requirements, permitted instruments, holding periods, news restrictions, leverage parameters, prohibited strategies, and evaluation windows. The rules displayed for the product you select form part of these Terms.\n\nYou are responsible for reviewing the applicable rules before trading and for monitoring your own performance. Data, spreads, fills, slippage, execution timing, and platform availability in a simulation may differ from a live market. Simulated performance is not evidence of future results or of the ability to trade profitably with real money.\n\nWe may invalidate activity, reset a challenge, suspend an account, or terminate access where activity appears to exploit a technical defect, manipulate the platform, evade a rule, use prohibited automation, copy another user's activity, or otherwise undermine the integrity of the assessment."],
  ["8. Prohibited conduct", "You may not use the Services to break the law; circumvent access or security controls; reverse engineer or scrape the platform; introduce malware; interfere with availability; falsify identity or payment information; sell, lease, or share access; manipulate scores or results; exploit pricing or data errors; or use the Services for money laundering, sanctions evasion, fraud, or another unlawful purpose.\n\nYou may not use a bot, algorithm, script, device, or third-party service in a way prohibited by the applicable product rules. Where automation is permitted, you remain responsible for its operation and for compliance with all limits. We may retain records and investigate suspected misuse to protect users, our providers, and the integrity of the Services."],
  ["9. Market data and third-party services", "Market data and other information may be supplied by third parties. It may be delayed, incomplete, inaccurate, interrupted, or unavailable. You may use it only through the Services and for your own permitted use. You may not redistribute, commercially exploit, or use it to create a competing service unless the relevant provider authorizes that use.\n\nPayment processors, authentication providers, hosting providers, charting services, analytics providers, and other third parties may have separate terms and privacy practices. We are not responsible for third-party services that we do not control, including their availability, content, security, or processing decisions."],
  ["10. Intellectual property", "The Services and their software, design, text, graphics, trademarks, logos, compilations, and content are owned by PrimePips or its licensors and are protected by applicable intellectual-property laws. Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access the Services for personal, lawful use.\n\nYou retain ownership of content you submit, but you grant us a worldwide, non-exclusive license to host, reproduce, process, and display it as needed to operate, secure, improve, and support the Services. Do not submit content that infringes another person's rights or contains confidential information you are not authorized to disclose."],
  ["11. Educational information and no advice", "The Services and their content are provided for general educational and informational purposes. Nothing on the platform is financial, investment, legal, tax, accounting, or trading advice, and no communication from PrimePips creates a recommendation to buy, sell, hold, or trade any instrument.\n\nTrading and financial markets involve substantial risk, including the possible loss of money. You should independently evaluate whether trading is appropriate for you and obtain professional advice where necessary. Never trade money you cannot afford to lose."],
  ["12. Availability and changes", "We may modify, pause, withdraw, or discontinue any feature, product, data source, rule set, or part of the Services. We may perform maintenance, impose limits, or temporarily suspend access to address security, capacity, legal, operational, or integrity concerns. We do not guarantee uninterrupted, error-free, secure, or continuously available access.\n\nIf a material change substantially reduces a paid feature before its stated period ends, we may provide a reasonable remedy where required by law or where we consider it appropriate. No remedy is promised for changes required by law, third-party withdrawal, misuse, force majeure, or events outside our reasonable control."],
  ["13. Privacy and communications", "Our Privacy Policy explains how we collect, use, disclose, retain, and protect personal information. By using the Services, you acknowledge that policy. You agree to receive transactional messages relating to your account, security, purchases, and support. Marketing messages may be controlled through the available unsubscribe mechanism.\n\nYou must not use support, chat, reviews, or community features to harass, threaten, impersonate, defame, discriminate against, or expose personal information about another person. We may moderate or remove communications that violate these Terms or applicable law."],
  ["14. Suspension and termination", "You may stop using the Services at any time. We may suspend or terminate access immediately if you breach these Terms, violate product rules, create legal or security risk, fail payment verification, engage in abuse, or if continued operation is not reasonably possible. We may also close inactive accounts in accordance with applicable law.\n\nOn termination, your license to use the Services ends. Provisions concerning payment obligations, intellectual property, disclaimers, limitations of liability, dispute resolution, and any provision that by its nature should survive termination will continue to apply."],
  ["15. Disclaimers", "TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICES ARE PROVIDED AS IS AND AS AVAILABLE, WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DISCLAIM WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, RELIABILITY, AVAILABILITY, AND THAT THE SERVICES WILL MEET YOUR EXPECTATIONS OR PRODUCE ANY PARTICULAR RESULT.\n\nWe do not warrant that simulated performance will correspond to live performance, that any strategy will be profitable, or that you will pass an assessment. No testimonial, example, ranking, projection, or historical result guarantees a future outcome."],
  ["16. Limitation of liability", "To the maximum extent permitted by law, PrimePips and its owners, officers, employees, affiliates, licensors, and providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, opportunities, goodwill, or business interruption arising from your use of or inability to use the Services.\n\nTo the maximum extent permitted by law, our total aggregate liability for claims arising out of the Services or these Terms will not exceed the amount you paid to PrimePips for the specific Services giving rise to the claim during the twelve months before the event. This limitation does not apply where liability cannot legally be limited."],
  ["17. Indemnification", "You agree to defend, indemnify, and hold harmless PrimePips and its affiliates, personnel, licensors, and providers from claims, losses, liabilities, damages, costs, and expenses, including reasonable legal fees, arising out of your breach of these Terms, unlawful conduct, misuse of the Services, infringement of third-party rights, or violation of product rules.\n\nWe may assume exclusive control of the defense of a matter subject to indemnification. You agree to cooperate reasonably and not settle a claim in a way that admits liability or imposes obligations on us without our prior written consent."],
  ["18. Disputes and governing law", "Before filing a formal claim, contact support with a clear description of the issue and the resolution you seek. The parties will attempt in good faith to resolve eligible disputes informally. Nothing prevents either party from seeking urgent relief where necessary to protect security, intellectual property, confidential information, or legal rights.\n\nThe governing law, venue, arbitration terms, and consumer protections applicable to your use of the Services depend on the jurisdiction identified in the checkout terms or an applicable written agreement. Mandatory rights in your place of residence are not waived by these Terms."],
  ["19. General terms", "These Terms, the applicable product rules, and policies expressly incorporated into them are the entire agreement concerning the Services. If any provision is held invalid or unenforceable, it will be modified to the minimum extent necessary and the remaining provisions will remain in effect. Our failure to enforce a provision is not a waiver.\n\nYou may not assign these Terms or your account without our written consent. We may assign these Terms in connection with a merger, reorganization, sale of assets, or operation of the Services. These Terms do not create a joint venture, partnership, employment relationship, or agency relationship."],
  ["20. Contact", "Questions about these Terms, an account, a payment, or a product rule should be directed through the support contact published in the Services. Include the email address associated with your account and enough information for us to locate the relevant transaction or account without sending passwords or payment credentials."],
] as const;

const supplementalSections = [
  ["21. Definitions", "For purposes of these Terms, account means the user profile and any simulated trading environment made available through that profile. Challenge means a defined assessment with stated parameters, rules, and a stated period. Content means text, data, images, audio, video, code, messages, results, and other material made available through the Services. Device means any computer, phone, tablet, or other equipment used to access the Services. Product rules means the rules and specifications displayed for a particular challenge or account, together with any updates that apply to that product.\n\nThe words including, includes, and such as are illustrative and do not limit the general meaning of the words that precede them. References to writing include electronic communications where permitted by law. Headings are included for convenience and do not change the meaning of a provision."],
  ["22. Reading product information", "Before purchasing, you are responsible for reviewing the product page, checkout summary, rule panel, and any linked information that describes the selected Service. These materials may specify the simulated starting balance, loss thresholds, profit objectives, permitted instruments, minimum activity, time limits, reset conditions, and other requirements. A product may differ from another product even where the product names or account sizes appear similar.\n\nScreenshots, examples, promotional illustrations, and historical demonstrations are not substitutes for the rules displayed for your specific purchase. If a product description conflicts with a later checkout summary, contact support before paying. Once you begin using a product, your use is governed by the product rules shown for that product and these Terms."],
  ["23. No custody of user funds", "PrimePips does not accept deposits, hold trading capital for users, manage user portfolios, or maintain a custodial balance on a user's behalf. Amounts displayed inside a simulated account are entries in a software environment and are not cash, electronic money, or a deposit owed to you. You should not send funds to an account number or wallet address unless the payment flow expressly identifies an authorized payment provider.\n\nYou remain responsible for confirming that a payment destination, invoice, currency, and amount are correct before authorizing payment. We are not responsible for transfers sent to an unofficial address, an impersonator, an incorrect network, or a payment channel that is not presented by the Services."],
  ["24. Simulated order processing", "Orders, positions, stop-losses, take-profits, pending orders, margin calculations, and other trading events in the platform are simulated events generated by software and data feeds. They do not constitute instructions sent to a live exchange, broker, liquidity provider, or other market venue. A simulated fill does not indicate that an equivalent fill could have been obtained in a live account.\n\nThe platform may calculate a result using a data point, spread, timestamp, rounding method, or price source that differs from another provider. We may correct an obvious technical error or recalculate a result when necessary to maintain consistent application of the product rules. A correction may change a displayed balance, score, or status."],
  ["25. Prices, candles, and timestamps", "Charts and quoted prices may reflect bid prices, ask prices, midpoint prices, indicative prices, delayed prices, or another methodology described by the relevant provider. The displayed chart is an aid to the simulated environment and should not be treated as a guaranteed record of every tradable price. Candle boundaries and server timestamps may differ from the clock on your Device.\n\nYou are responsible for checking the platform's displayed time zone and for considering the effect of market closures, daylight-saving changes, holidays, gaps, spreads, and data interruptions. We are not responsible for a decision made solely from a chart or quote that is delayed, stale, incomplete, or misunderstood."],
  ["26. Risk limits and account status", "A loss limit, drawdown limit, or other risk threshold is applied according to the calculation method stated in the applicable product rules. The method may consider balance, equity, closed trades, open trades, commissions, swaps, fees, floating loss, daily resets, or other factors. A threshold can be reached before a trade is closed or before the result is visible in every part of the interface.\n\nAccount statuses are labels used by the Services to record the state of an assessment or access entitlement. Active, pending, failed, passed, closed, restricted, or similar labels do not represent the existence of live funds or an obligation to issue a reward. A status may be corrected after review of data, payment, rule compliance, or a technical incident."],
  ["27. Consistency and behavioral review", "Where a product includes a consistency requirement, the purpose is to evaluate whether activity reflects a reasonably coherent approach rather than a single isolated result. The applicable rule may examine concentration of gains, exposure, trade size, holding time, instrument selection, timing, or another stated measure. No consistency metric should be interpreted as a prediction of live profitability.\n\nWe may review activity manually or through automated controls. A review can take account of the full history available to us, including activity that was initially marked as compliant. We may ask for information about the person using an account, the source of an instruction, or the circumstances of unusual activity. Review does not convert the account into a live account or create a right to payment."],
  ["28. Drawdown and loss calculations", "The product rules may use static drawdown, trailing drawdown, daily drawdown, relative drawdown, or another loss calculation. The reference value, reset time, treatment of open positions, and treatment of fees will be stated where applicable. You are responsible for understanding that a loss limit may move, reset, or be evaluated at a time different from the time you expect.\n\nIf a calculation depends on data that later becomes available or is corrected, the final evaluation may differ from an interim display. We may preserve the original event log and use a corrected calculation when the original output resulted from an outage, stale price, duplicated event, bad timestamp, or other error. You agree to review a rule before relying on any threshold."],
  ["29. Trading styles and prohibited patterns", "A product may restrict strategies that create artificial, non-representative, or abusive results within the simulation. Examples may include exploiting a quote delay, submitting excessive orders to overload a feed, coordinating offsetting positions across accounts, using a platform defect, reproducing another person's trades without authorization, or deliberately creating activity that defeats the stated purpose of the assessment.\n\nA strategy is not prohibited merely because it loses or wins, uses a particular technical method, or produces a particular return. The question is whether the activity complies with the specific product rules and uses the Services in a genuine, good-faith manner. When a rule is unclear, ask support before placing the relevant trade."],
  ["30. Multiple accounts and related activity", "If multiple accounts are permitted, each account must be used according to the product rules and any stated limits. We may compare account information, Devices, network signals, trading behavior, order timing, payment information, and other indicators to detect account sharing, coordinated activity, or attempts to obtain an unfair assessment advantage. These checks may be automated and may produce a temporary review status.\n\nSimilarity between two independent traders does not automatically establish misconduct. However, we may request reasonable evidence or explanation where the overall pattern creates a legitimate integrity concern. We may consolidate, restrict, reset, or close related accounts where necessary to enforce a rule or prevent circumvention."],
  ["31. Automation and software tools", "If the product rules permit an expert advisor, script, API, copy tool, or other automation, that permission is limited to the stated use. You must ensure the tool does not overload the platform, submit malformed requests, exploit latency, bypass a restriction, impersonate another user, or otherwise interfere with the Services. You are responsible for licensing, configuration, maintenance, and security of any third-party tool.\n\nA third-party tool may continue placing orders after you believe it has stopped. Disconnect or disable it promptly if it behaves unexpectedly. We may suspend automated access while investigating repeated errors, excessive requests, unusual order patterns, or a security concern. Permission to use automation does not imply that the same tool is suitable for real-money trading."],
  ["32. Account security and verification", "You must use a unique password, protect authentication codes, keep Devices reasonably secure, and avoid logging in through a compromised or public Device where sensitive information may be captured. We may require email, identity, age, location, payment, or other verification before enabling a feature or completing a support request. Verification information must be accurate and must belong to the person using the account.\n\nDo not send passwords, one-time codes, private keys, full card numbers, or recovery phrases to support. We will not ask for a secret authentication code through an unsolicited message. Tell us promptly about suspected credential theft, unauthorized payments, impersonation, or account takeover so that protective action can be considered."],
  ["33. Identity and location restrictions", "Some Services may not be available in every country, territory, state, or region. We may use information supplied by you and reasonable technical signals to determine whether a Service can be offered. Do not disguise your location, use another person's identity, or provide inaccurate information to bypass a geographic, legal, sanctions, age, or product restriction.\n\nA change in residence or legal status may affect your ability to use an existing account. You must notify us if information relevant to eligibility changes. Access from a permitted country does not make use lawful in another jurisdiction, and you are responsible for understanding local restrictions before accessing the Services while traveling."],
  ["34. Payment authorization and verification", "By submitting a payment, you confirm that you are authorized to use the selected payment method and that the billing information is accurate. Payment providers may perform verification, apply fraud controls, decline a transaction, reserve funds, or request additional information. PrimePips does not control a provider's approval decision, settlement timing, exchange rate, or fee schedule.\n\nWe may limit payment attempts, delay activation, or suspend access while a transaction is being confirmed. If a payment is reversed or charged back, any related access may be disabled and the transaction may be investigated. You remain responsible for amounts properly owed under these Terms, subject to applicable consumer and payment law."],
  ["35. Taxes and reporting", "You are responsible for determining whether your purchase, use of the Services, or any amount received under a separate written arrangement has tax consequences for you. You are also responsible for providing accurate tax or billing information where requested and for complying with reporting obligations in your jurisdiction. PrimePips does not provide tax advice.\n\nWe may collect, verify, or disclose information where required by law, payment networks, tax authorities, or an official request. A simulated balance, simulated profit, simulated loss, score, or account size is not a statement about your taxable income, assets, or liabilities. Obtain independent professional advice if you are uncertain."],
  ["36. Promotional offers and referrals", "Promotional codes, referral credits, discounts, trials, contests, and other offers are subject to the conditions presented with the offer. Unless expressly stated, an offer cannot be combined with another offer, transferred, sold, exchanged for cash, or applied retroactively. We may set eligibility limits, expiration dates, geographic limits, and usage caps.\n\nReferral activity must be genuine and must not involve spam, misleading claims, self-referrals, automated registrations, paid search practices that misuse our marks, or promises that users will receive real capital or rewards. We may cancel credits and restrict accounts associated with abusive or misleading promotion."],
  ["37. Reviews, testimonials, and user submissions", "If you submit a review, testimonial, suggestion, screenshot, question, trade journal entry, or other material to us or a community feature, you represent that it is truthful to the best of your knowledge, does not identify another person without permission, and does not contain confidential or unlawful material. Do not present a simulated result as a real financial return.\n\nSubject to applicable law and our Privacy Policy, you grant us permission to use, reproduce, adapt, publish, translate, and display a submission for operating, improving, moderating, or promoting the Services. We may remove a submission that is inaccurate, abusive, promotional, off-topic, infringing, or inconsistent with the purpose of the community."],
  ["38. Communications and electronic records", "You consent to receiving agreements, notices, invoices, account alerts, rule updates, and support responses electronically. An email, in-app message, dashboard notice, or other electronic record may satisfy a legal writing or notice requirement where permitted by law. Keep your contact details current and check the address associated with your account.\n\nA notice is considered received when sent to the address or account location we have on record, even if a filter, outage, full inbox, or Device setting prevents you from reading it. This does not remove any notice requirements imposed by mandatory law. You may request a copy of an applicable record through support."],
  ["39. Support boundaries", "Support can explain how the Services operate, identify the product rules associated with a transaction, help troubleshoot technical access, and receive complaints. Support cannot provide investment advice, guarantee a result, change a rule retroactively, promise a refund outside policy, or turn simulated activity into live trading. A friendly or informal support message does not amend these Terms.\n\nWe may use reasonable queues, business hours, identity checks, and ticket limits to protect support quality and account security. Do not open repeated tickets for the same issue to obtain a different answer. If a support response contains an error, notify us with the relevant ticket so it can be corrected."],
  ["40. Complaints and error reports", "If you believe a displayed result, charge, account status, or product rule was applied incorrectly, contact support promptly with your account identifier, relevant timestamps, order references, and a description of the issue. Do not include secrets or unnecessary personal data. We may need logs from the platform, payment provider, market-data provider, and Device to investigate.\n\nWe will assess reports using the information reasonably available at the time. A report does not pause a challenge clock or automatically reverse a status. We may provide an explanation, correction, or other response where appropriate, but no investigation result should be interpreted as a representation that the account contains real funds or that a reward is owed."],
  ["41. Platform maintenance and incidents", "The Services may be unavailable during planned maintenance, emergency maintenance, provider outages, releases, security response, database recovery, or other operational events. We may announce maintenance through the dashboard or another channel, but advance notice is not always possible. During an incident, displayed data may be incomplete or unavailable and orders may be delayed, rejected, duplicated, or shown out of sequence.\n\nDo not rely on the platform as a backup for a live trading system or as a sole record of your personal activity. You should keep any permitted personal records you need for educational purposes. We may restore data from a backup or replay events after an incident, which can change interim results without changing the simulated nature of the account."],
  ["42. Security investigations", "We may monitor technical and account activity to maintain security, detect fraud, investigate abuse, protect providers, and enforce these Terms. Monitoring may include authentication events, IP addresses, Device identifiers, browser information, request patterns, order events, payment signals, and communications relevant to a report. Processing is subject to our Privacy Policy and applicable law.\n\nIf we identify a credible security concern, we may require a password reset, revoke sessions, restrict features, hold an account for review, or preserve relevant records. We may disclose information to service providers, professional advisers, law enforcement, regulators, or affected parties when reasonably necessary and legally permitted."],
  ["43. Confidentiality and sensitive information", "You may receive non-public information about product development, incidents, account reviews, support procedures, or other users. Use such information only to use the Services lawfully and do not disclose it unless authorized or legally required. This duty does not apply to information that becomes public without your breach or that you can demonstrate you already lawfully possessed.\n\nWe may ask you not to publish information that would expose a security vulnerability before we can investigate it. This does not prevent you from making a truthful complaint, reporting unlawful conduct, seeking professional advice, or exercising a legal right. Do not upload confidential information belonging to an employer, client, broker, or another person."],
  ["44. Accessibility and reasonable requests", "We aim to make the Services usable by people with different needs. If a technical or communication barrier prevents you from understanding a product rule or accessing an account, contact support with a description of the barrier and the assistance requested. We may offer an alternative format or reasonable process where feasible and lawful.\n\nAn accommodation does not change the financial, simulated, security, or eligibility requirements of a product unless we expressly confirm that change in writing. You remain responsible for reviewing the information provided and for ensuring that a Device, browser, translation, or assistive tool renders the relevant information correctly."],
  ["45. Children and protected persons", "The Services are not directed to children who are below the minimum age required to enter a contract or use the applicable product in their jurisdiction. Do not create an account for another person who cannot legally accept these Terms. If you believe a child has submitted personal information or created an account, contact support with sufficient information for us to investigate.\n\nA parent, guardian, or other representative may not use the Services on behalf of another person unless that arrangement is lawful, expressly permitted by the product, and disclosed to us. We may close an account where age, capacity, identity, or authorization cannot be verified."],
  ["46. International use", "The Services may be operated from and supported by people or providers in countries different from your own. You are responsible for complying with export controls, import restrictions, sanctions, local financial-promotion rules, consumer requirements, data laws, and other laws that apply when you access the Services. Availability of a webpage does not constitute an invitation or authorization to use every product in every jurisdiction.\n\nYou may not use the Services for a person, organization, country, or territory subject to applicable sanctions or restrictions. We may block access, cancel a transaction, or request information when necessary to comply with a legal or provider requirement."],
  ["47. Force majeure", "We are not responsible for delay, interruption, loss, or failure caused by events beyond our reasonable control, including natural disasters, severe weather, fire, war, civil unrest, terrorism, epidemic, labor disruption, government action, power or network failure, cyberattack, provider failure, market closure, exchange outage, data-source interruption, payment-network problem, or a change in law.\n\nDuring such an event, we may pause the affected Services, extend or close a challenge where reasonable, restore data, or take another operational step. We do not promise that an event will result in an extension, refund, reset, compensation, or other remedy unless required by law or expressly confirmed by us."],
  ["48. Assignment and corporate changes", "You may not sell, transfer, pledge, delegate, or assign an account, purchase, license, claim, or right under these Terms without our prior written consent. Any attempted transfer that violates this section may be treated as invalid. We may rely on the identity and payment information associated with the account when communicating with you.\n\nWe may assign or transfer these Terms, the Services, or related rights and obligations to an affiliate, successor, purchaser, or service provider as part of a restructuring, financing, merger, acquisition, asset sale, or ordinary operation. Such a transfer does not reduce mandatory rights that apply to you."],
  ["49. No waiver and cumulative remedies", "A delay or failure to exercise a right under these Terms does not waive that right. A waiver is effective only if made in writing by an authorized representative and only for the specific instance described. A single exception or accommodation does not create a general exception for you or another user.\n\nRights and remedies under these Terms are cumulative and may be used separately or together to the extent permitted by law. We may seek injunctive or equitable relief where monetary damages would not adequately address misuse of intellectual property, confidential information, security controls, or the Services."],
  ["50. Interpretation and entire agreement", "These Terms should be interpreted to give lawful effect to each provision. If a provision is ambiguous, the interpretation that best preserves the stated purpose of the Service and the applicable product rules should be preferred, subject to mandatory consumer protections. The English-language version controls where translations differ, unless mandatory law requires otherwise.\n\nThese Terms, the product rules, the checkout summary, the Privacy Policy, and any other policy expressly incorporated by reference form the agreement between you and PrimePips about the Services. Marketing language, social media posts, informal statements, and third-party commentary do not amend that agreement unless incorporated in a written update."],
  ["51. Changes to these Terms", "We may update these Terms to reflect changes in the Services, product structure, law, security practices, providers, or business operations. The current effective date appears at the top of this page. For a material change, we may provide notice through the Services or the email associated with your account where required or appropriate.\n\nYou should review the Terms before each new purchase and periodically while using an existing account. If you do not accept a revised version, stop using the affected Services and contact support about any available cancellation or transition process. Continued access after the effective date means you accept the revised Terms to the extent permitted by law."],
  ["52. No expectation of real rewards", "For clarity, no purchase, account status, displayed result, successful challenge, leaderboard position, referral activity, testimonial, marketing statement, or support message creates an expectation that you will receive a cash payment, trading profit, funded capital, prize, commission, payout, or other real reward. Any exception must be stated in a separate written agreement that identifies the parties, the applicable conditions, and the legally permitted consideration.\n\nYou should purchase a Service only if you value the simulated assessment, software access, educational practice, and related features on their own. Do not purchase based on an assumption that a simulated result will become money, that PrimePips will finance your personal trading, or that a future arrangement is guaranteed."],
  ["53. User acknowledgements", "By using the Services, you acknowledge that you have had an opportunity to read these Terms, that the simulation and no-rewards disclosure is material to your decision, and that you understand the difference between simulated results and real financial performance. You acknowledge that you are not relying on a promise of guaranteed income, guaranteed access, guaranteed success, or guaranteed payment.\n\nYou also acknowledge that you are responsible for your own decisions, Device, credentials, payment authorization, legal compliance, and review of applicable rules. If you do not understand an important provision, do not proceed until you have obtained an explanation or independent professional advice."],
  ["54. Contact and formal notices", "Questions, complaints, legal notices, and requests concerning these Terms should be sent through the official support or contact channel identified on the current website. A message sent through an unofficial social account, a third-party chat, or a personal address is not necessarily received by PrimePips. Include a subject that identifies the issue and enough non-sensitive detail for us to respond.\n\nYou remain responsible for keeping copies of receipts, policy versions, support tickets, and other records relevant to your use. We may maintain electronic records of notices, consent, account events, payments, and communications. Those records may be used to administer the Services and resolve a dispute, subject to applicable law and our Privacy Policy."],
] as const;

const finalSections = [
  ["55. Browser and Device compatibility", "The Services may support only certain browsers, operating systems, screen sizes, or network configurations. We may stop supporting an older version when continuing support creates security, reliability, or provider-compatibility problems. You are responsible for installing updates and using a supported environment.\n\nA browser extension, firewall, VPN, proxy, privacy tool, ad blocker, translation layer, or corporate network may interfere with authentication, charts, order events, payment pages, or account notices. We do not promise that every combination of software and network settings will work. Troubleshoot locally and contact support with technical details rather than repeatedly attempting actions that may create duplicate requests."],
  ["56. Network delays and user actions", "Information sent between your Device and the Services may be delayed, lost, duplicated, reordered, or blocked. A button press, keyboard shortcut, API call, or other instruction may be processed after the interface changes or may be processed more than once if you repeat it. Review confirmations and account history before submitting a second request.\n\nThe timestamp shown on your Device is not controlling evidence of when an event reached our systems. Server logs, provider records, and event histories may be used to determine sequence. We are not responsible for a result caused by a weak connection, a sleeping Device, a browser tab that was left open, a local clock error, or a user action made without checking the current state."],
  ["57. Account history and record retention", "We may retain account records, event logs, support tickets, payment records, rule versions, consent records, and relevant technical information for as long as reasonably necessary to operate the Services, investigate disputes, satisfy legal duties, prevent abuse, and maintain business records. The retention period may vary by record type and jurisdiction.\n\nYou may request access, correction, or deletion of personal information where available under applicable law, subject to identity verification and lawful exceptions. Deleting a record from a dashboard does not necessarily delete a system record that must be retained. Our Privacy Policy explains the applicable process and limitations."],
  ["58. Data accuracy and user corrections", "You must correct registration, billing, contact, and eligibility information when it changes. If you discover that a record is wrong, notify support promptly and identify the specific field, event, or transaction. We may ask for evidence before changing a record, particularly where a change could affect access, payment, identity, or an account review.\n\nWe may correct our own records when reliable evidence shows that a display, import, calculation, or synchronization was inaccurate. A correction is not an admission of wrongdoing and does not create a general right to a reset or refund. Data that cannot be verified may remain unchanged or may be removed where appropriate."],
  ["59. Third-party links and integrations", "The Services may contain links to websites, applications, platforms, brokers, payment providers, social communities, or educational resources operated by third parties. A link does not mean that PrimePips endorses the third party, its products, its claims, or its security. Review the third party's terms and privacy notice before providing information or using its service.\n\nAn integration may stop working, change permissions, return incomplete data, or require a new authorization. You are responsible for revoking an integration you no longer use and for checking what information it can access. We are not responsible for third-party content, transactions, losses, or decisions made outside the Services."],
  ["60. Open-source and licensed components", "The Services may include software distributed under open-source or third-party licenses. Those components remain subject to their applicable license notices and conditions. Nothing in these Terms removes rights that a component license grants to you or imposes restrictions that the license does not permit.\n\nYou may not copy, modify, distribute, decompile, or create derivative works of proprietary parts of the Services except as expressly permitted by law or by written authorization. If you identify a licensing or attribution issue, contact support with the component name and the relevant location so it can be reviewed."],
  ["61. Copyright complaints", "If you believe that content made available through the Services infringes your copyright, send a notice through the official contact channel with enough information to identify the protected work, the allegedly infringing material, your contact information, and a statement that the information is accurate to the best of your knowledge. Do not submit a false or abusive complaint.\n\nWe may remove or restrict material while a report is reviewed and may notify the person who submitted it or the person who supplied the material. Repeat infringement or knowingly false reports may result in account action. This process does not decide ownership disputes that require a court or another competent authority."],
  ["62. Trademark use", "PrimePips names, logos, product names, visual marks, and related branding may be trademarks or trade dress owned by PrimePips or its licensors. You may not use them in a domain name, social handle, advertisement, application, product, or publication in a way that suggests sponsorship, affiliation, endorsement, or official status without written permission.\n\nYou may make truthful references to the Services for legitimate commentary or review, provided the reference does not mislead users, reproduce protected branding as the main identity of your service, or imply that you represent PrimePips. We may require changes to confusing or unauthorized uses."],
  ["63. Fair use of platform resources", "The Services are shared resources. Use reasonable request rates, storage, bandwidth, chart subscriptions, messaging, and support capacity. Do not run a scanner, crawler, script, or repeated refresh that creates unnecessary load or attempts to discover private endpoints. Do not use a shared feature to distribute unsolicited advertising, malware, or content unrelated to its purpose.\n\nWe may throttle, queue, limit, or remove activity that consumes disproportionate resources. A limit may apply temporarily, permanently, to one feature, or to an entire account. Resource limits are not a statement about your trading performance and do not make a simulated account live."],
  ["64. Community standards", "Where the Services provide a community, leaderboard, chat, comment, or social feature, communicate in a way that is truthful, relevant, and respectful. Do not encourage unlawful conduct, publish personal data, harass a user, impersonate staff, coordinate prohibited trading activity, manipulate rankings, or claim that simulated profits are guaranteed.\n\nModerators may remove material, restrict posting, mute an account, or refer a matter for review. Moderation decisions may be based on context and available evidence and may not be explained in detail where doing so would expose security controls or another person's private information."],
  ["65. User responsibility for decisions", "You choose whether, when, and how to use the Services. The existence of a rule, warning, chart, score, notification, or support answer does not require you to take a particular action and does not transfer responsibility for your decision to PrimePips. You should pause use if you are confused, distressed, under pressure, or unable to assess the consequences of continuing.\n\nNo interface is a substitute for a personal risk plan. Set limits for time and spending, understand that a challenge fee may be lost, and do not borrow money or use funds needed for essential expenses to access the Services. Educational practice should remain within your financial and personal means."],
  ["66. Responsible communication of results", "If you describe your experience publicly, distinguish simulated performance from live performance and identify material conditions that affect the result. Do not present an account size as capital entrusted to you, a simulated balance as cash, or a challenge pass as proof of professional qualification. Do not make claims about typical outcomes unless you have reliable evidence and are legally permitted to make them.\n\nWe may ask you to correct a statement that materially misrepresents the Services or another person's experience. Nothing in this section prevents a truthful review, criticism, report to a regulator, or lawful discussion of your own experience."],
  ["67. No professional relationship", "Access to the Services does not make you a client, customer of an investment adviser, employee, contractor, agent, representative, partner, franchisee, broker, dealer, or beneficiary of PrimePips. You may not make commitments, accept money, enter contracts, or communicate on behalf of PrimePips unless expressly authorized in writing.\n\nNothing in a dashboard, badge, score, certificate, affiliate relationship, or community role gives you authority to represent PrimePips. If you are asked by another person to pay money, share credentials, or provide personal information in exchange for a claimed PrimePips opportunity, verify it through the official support channel before acting."],
  ["68. Financial promotions and regulated activities", "PrimePips does not authorize you to market the Services as an investment, offer financial products, solicit deposits, manage another person's money, or provide regulated advice. If you discuss the Services in a jurisdiction with advertising or financial-promotion rules, you are responsible for complying with them. Do not use our name to support a claim that a user can expect income or a guaranteed result.\n\nWe may restrict or close an account used to promote the Services in a misleading, unauthorized, or unlawful manner. A referral relationship does not exempt you from disclosure obligations, platform rules, consumer laws, or the requirement to make clear that accounts and results are simulated."],
  ["69. Security of payment credentials", "Payment card numbers, bank credentials, wallet keys, and authentication secrets should be entered only into the authorized payment or login interface presented by the Services or the named provider. PrimePips staff will not need your full secret credential to investigate a transaction. Redact sensitive information before sending screenshots or receipts.\n\nIf you believe a payment method was used without authorization, contact the payment provider promptly and notify support. We may preserve relevant records, suspend affected access, or request evidence. We cannot reverse a transaction controlled solely by a bank, wallet, card network, or other provider."],
  ["70. Currency conversion and settlement", "When a product is displayed in one currency and charged in another, the amount shown by the payment provider may differ because of conversion timing, provider rates, bank fees, taxes, or settlement rules. PrimePips does not guarantee a particular exchange rate unless the checkout expressly states one.\n\nA payment reference, invoice number, or transaction hash helps locate a payment but does not prove that a payment was authorized, settled, or associated with the correct account. Do not make duplicate payments while a transaction is pending without first checking its status through the official payment flow."],
  ["71. Fraud prevention and transaction holds", "We may place a transaction or account on hold when automated or manual checks identify unusual velocity, mismatched information, repeated failures, a dispute, a sanctions concern, an account takeover signal, or another risk indicator. A hold is an investigative step and is not necessarily a conclusion that you acted improperly.\n\nDuring a hold, we may request information that is reasonably necessary to verify the transaction or account. Do not send more information than requested. We may cancel a transaction or decline access when the concern cannot be resolved, when a provider refuses settlement, or when continuing would create legal or security risk."],
  ["72. Refund review factors", "When reviewing a refund request, we may consider the product purchased, the time since purchase, whether access was delivered, whether a challenge was started, activity performed, technical records, payment status, prior refunds, and the refund policy shown at checkout. These factors do not eliminate mandatory rights or a provider's independent obligations.\n\nA refund, credit, reset, or goodwill adjustment provided once does not establish a precedent or guarantee the same result in another case. We may provide a response through the account email or support ticket. Keep the reference number for follow-up and do not submit card data or authentication secrets in a request."],
  ["73. Product retirement and migration", "We may retire a product, replace a data source, change a platform integration, or migrate account records. If migration is offered, you may need to accept updated technical requirements or complete an account verification step. A migration may change how information is displayed while preserving the underlying record relevant to the applicable product rules.\n\nA retired product may no longer accept new activity even if a page or cached link remains accessible. We are not required to maintain an obsolete feature indefinitely. Where law or an express product commitment requires notice or a remedy, we will provide the applicable notice or remedy."],
  ["74. Interpretation of simulated examples", "Examples in the Services may show a hypothetical entry, exit, balance, drawdown, risk percentage, or result. An example explains a calculation or workflow; it is not a promise that the same event will occur for you. Examples may omit commissions, delays, data gaps, eligibility conditions, or other variables unless the example says otherwise.\n\nDo not infer typical performance, pass rates, payout rates, or financial outcomes from an isolated example, screenshot, testimonial, or demonstration. If a numerical example conflicts with the current product rules, the current product rules control, subject to correction of an obvious error."],
  ["75. Final confirmation", "By proceeding beyond this page to register, purchase, or use a Service, you confirm that you understand the central disclosure: PrimePips accounts are simulated accounts created to test trading skills, and no real rewards or financial returns should be expected. You confirm that the fee is paid for access to a simulated assessment and related Services, not for real trading capital.\n\nYou also confirm that you have read the applicable product rules, understand that simulated performance does not predict live performance, and accept responsibility for your decisions. This confirmation does not limit any right that cannot legally be limited and does not replace professional legal or financial advice where such advice is appropriate."],
  ["76. Simulation and rewards disclosure", "ALL PRIMEPIPS ACCOUNTS ARE SIMULATED ACCOUNTS CREATED TO TEST TRADING SKILLS. TRADES ARE NOT EXECUTED WITH REAL MARKET CAPITAL THROUGH THE PRIMEPIPS PLATFORM, AND NO REAL REWARDS, PROFITS, PAYOUTS, OR OTHER FINANCIAL RETURNS ARE TO BE EXPECTED.\n\nAny balance, equity, profit, loss, performance percentage, leaderboard position, account size, or other result shown in the Services is a simulated result for assessment, demonstration, or educational purposes. A displayed result is not money held for you, does not represent a claim against PrimePips, and may not be withdrawn, redeemed, converted, or assigned unless a separate written agreement expressly says otherwise and applicable law permits it.\n\nYou must read this section before purchasing or using the Services. Nothing in the website, dashboard, advertising, emails, educational content, or support communications changes the simulated nature of the accounts or creates an expectation of a real financial reward."],
] as const;

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-20">
        <section className="border-b border-border bg-gradient-hero py-16">
          <div className="container mx-auto max-w-4xl px-4">
            <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-primary">Legal</p>
            <h1 className="mb-4 text-4xl font-serif font-bold text-foreground md:text-5xl">Terms and Conditions</h1>
            <p className="text-muted-foreground">Effective date: August 19, 2026</p>
          </div>
        </section>
        <article className="container mx-auto max-w-4xl px-4 py-12">
          <div className="space-y-10">
            {[...sections, ...supplementalSections, ...finalSections].map(([title, content]) => (
              <section key={title}>
                <h2 className="mb-3 text-2xl font-serif font-semibold text-foreground">{title}</h2>
                <div className="space-y-4 text-[15px] leading-7 text-muted-foreground">
                  {content.split("\n\n").map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
                </div>
              </section>
            ))}
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
}